# Generated by Django 2.1.9 on 2019-06-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190617_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='auther',
        ),
    ]
