# Generated by Django 2.2.2 on 2019-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='auther',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
