# Generated by Django 2.2.2 on 2019-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='auther',
            field=models.CharField(default='saadat', max_length=200),
        ),
    ]
