# Generated by Django 2.2.2 on 2019-06-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190618_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='auther',
        ),
    ]
