# Generated by Django 2.2.4 on 2019-08-03 13:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190803_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
