# Generated by Django 2.2.4 on 2019-08-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190803_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='auther',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
