# Generated by Django 2.2.4 on 2019-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190804_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='auther',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
