# Generated by Django 2.2.4 on 2019-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190804_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='auther',
            field=models.CharField(default='someone', max_length=200),
        ),
    ]
