# Generated by Django 2.2.4 on 2019-08-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
