# Generated by Django 2.2.4 on 2019-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='posts.Profile'),
        ),
    ]
